### ISSUE TITLE
No provision for testing angular app? 

### ISSUE THREAD

**Issue by sybarite** [Kaylors/kangular-plate#1]
Definitely needs a starting point to add angular protractor files required for testing the app. Without it your app is bound to shipped buggy.

**Comment by Kaylors** [comment]
I agree. Testing is very important. But one of the reasons I built a minimalistic boilerplate of my own is because all the others out there are bloated with tests. This boilerplate is NOT meant for large projects. Only small hobby projects. Add to it as you please.

Or if you can come with the LEAST-hassle testing integration, submit a PR.
